### ISSUE TITLE
Support traefik sticky sessions

### ISSUE THREAD

**Issue by Sechmann** [nais/naiserator#106]
https://docs.traefik.io/configuration/backends/kubernetes/

Specifically setting `traefik.ingress.kubernetes.io/affinity: "true"` on created ingress resources.
With a field like:
`.spec.sticky: true/false` in the application spec

**Comment by jhrv** [comment]
should this be supported (if at all possible) on GCP as well?

**Comment by VegarM** [comment]
In GCP we use istio-ingressgateway instead of traefik, and thus would have to solve this using a DestinationRule.
https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/
```
 apiVersion: networking.istio.io/v1alpha3
 kind: DestinationRule
 metadata:
   name: bookinfo-ratings
 spec:
   host: ratings.prod.svc.cluster.local
   trafficPolicy:
     loadBalancer:
       consistentHash:
         httpCookie:
           name: user
           ttl: 0s
```
