### ISSUE TITLE
Rules are required when defining a accesspolicy

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#109]
When you define a accessPolicy you are required to have a `spec.accessPolicy.outbound.rules` defined. 

Example of nais.yaml that should be valid:

```
spec:
  accessPolicy:
    outbound:
      external:
        - host: myexternalhost.no
```
