### ISSUE TITLE
Mulighet for å mounte inn ConfigMap som environment-variabler

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#136]
Det er ytret ønske om mulighet til å få lastet inn configmaps som envs, og ikke bare filer.
kan legges under `spec.configmaps.env`, og gjøres så likt som `spec.secrets`.

Helt likt blir det dessverre ikke, da vi allerede har definert `spec.configmaps.files`, mens i `spec.secrets` har vi gått for `type`.

Vi må også gjøre det veldig tydelig for brukerene at endringer i configmaps ikke gjør at podene som bruker det restartes og tar i bruk verdiene (dette er et problem vi kan løse på et senere stadie)

**Comment by jhrv** [comment]
Sjekket i clusterene, og finner ingen som bruker det. Så trenger ikke tenke på bakoverkompabilitet her

**Comment by Kyrremann** [comment]
Snakket litt om dette i dag, og vi lurer litt på å gå bort fra systemet vi har nå med `spec.configmap` og `spec.secrets`, og spesielt `type` og bruk av defaults. Det vi ønsker er å gjøre det mest mulig likt som vanilla.

Vanilla:
```
envFrom:
  - configMapRef:
    name: special-config
```
og
```
env:
  - name: SECRET_USERNAME
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: username
```
Hos oss
```
env:
  from: secret|env|tom
  name: name-of-configmap-secret
```
Dette må da merges inn sammen nåværende oppførsel. Kan hende det er bedre å lage en egen `envFrom`, for å unngå valideringsutfordringer med å ha forskjellig oppførsel på vanlig env, og fra configmap/secret.

For filer er det litt annerledes.
Vanilla:
```
volumeMounts:
  - name: config-volume
    mountPath: /etc/config
```
Secrets er likt, er `volumes` som er annerledes.

Hos oss kan vi skrive
```
files:
  from: secrets|configmap
  name: name-of-configmap-secret
  path: /some/non/default/path
```

**Comment by ambientsound** [comment]
Hva med:

```
spec:
  env:
    - name: foo
      value: bar
    - configMap: foobar
    - configMap: lol
    - secret: hehe
  files:
    - configMap: foobar
      mountPath: /moo
    - secret: hehe
      mountPath: /mooz
```

**Comment by jhrv** [comment]
slik jeg ser det blir spørsmålet hva som skal være toppnivå:
`envFrom` og `filesFrom` eller `secrets` og `configMaps`

Hvis man kollapser type og navn som egne felter blir dette forskjellen:

Alternativ 1:
```
spec:
  env: ...
  envFrom: 
    - secret: my-secret
    - configMap: my-cm
  
  fileFrom:
    - secret: my-secret-file
      mountPath: /var/run/secrets
    - configMap: my-cm-file
      mountPath: /my/config/path
```
vs

Alternativ 2:
```
spec:
  env: ...
  secrets:
    - env: my-secret
    - file: my-secret-file
      mountPath: /var/run/secrets
  
  configMaps:
    - env: my-cm
    - file: my-cm-file
      mountPath: /my/config/path
```

Her syns jeg det første alternativet leser best, da det i alternativ 2 ikke er intuitivt at fordi key er `env` at det betyr at det er måten det sources inn på. 
I alternativ 1 derimot leser det som  "{env,file} from {secret/configmap}", som jeg syns er veldig forklarende. 
Så derfor er det mer naturlig å ha eksplisitt felt for type i alternativ 2 (`type` er også kanskje en dårlig beskrivelse av hvordan det sources), som også gjør det litt mer verbost. 

Stemmer derfor for @ambientsound sitt forslag hvis vi skal gjøre om på dette nå
