### ISSUE TITLE
HPA som rapporterer <unknown>/50% hindrer nedskalering

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#144]
Vault-sidecar og  secure-logs sidecar har ikke `resouces` satt, som gjør at HPA ikke kan lese ut ressursene. Dette gjør at HPA ikke vil skalere ned en app etter den har blitt oppskalert.

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
> If multiple metrics are specified in a HorizontalPodAutoscaler, this calculation is done for each metric, and then the largest of the desired replica counts is chosen. If any of these metrics cannot be converted into a desired replica count (e.g. due to an error fetching the metrics from the metrics APIs) and a scale down is suggested by the metrics which can be fetched, scaling is skipped. This means that the HPA is still capable of scaling up if one or more metrics give a desiredReplicas greater than the current value.

Kan hende vi kan løse dette med å spesifisere hvilke pod vi skal lese ressursene fra.

**Comment by terjesannum** [comment]
Bruk dette i container specene på secure-logs sidecarene:

secure-logs-fluentd:
```
        resources:
          requests:
            cpu: 10m
            memory: 200m
```

secure-logs-configmap-reload:
```
        resources:
          requests:
            cpu: 10m
            memory: 50m
```
