### ISSUE TITLE
Network policy ingress for prometheus is not created

### ISSUE THREAD

**Issue by terjesannum** [nais/naiserator#147]
Applications with prometheus scraping enabled does not allow prometheus to scrape them. An ingress for prometheus has to be added to the application network policy:

```
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: istio-system
      podSelector:
        matchLabels:
          app: prometheus
```
