### ISSUE TITLE
Use EnvVars to configure the application (AKA no Fasit)

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#15]
Naiserator should make use of ConfigMaps instead of Fasit as a mechanism to provide the application with environment variables.

Note that this assumes that secrets are handled in a separate mechanism (currently Vault)

Todays situation is that the developers define resources in Fasit, e.g. a RestService like this:
```
alias: somesvc
url: https://someurl.no
```
and refer to it in their nais.yaml under fasitResources by *alias*

When the application is deployed, naisd will read the manifest, fetch the resource from Fasit, transform the key into envvar format (SOMESVC_URL) and add it to the PodSpec. 

What we now suggest, is that instead of putting the configuration in Fasit, we place the environment variables directly in ConfigMaps, and refer to those in the application resource (equivalent to nais.yaml).

We can have a ConfigMap like this 
```
  apiVersion: v1
    kind: ConfigMap
    metadata:
      name: myapp-config
    data:
      SOMESVC_URL: https://...
      MY_RANDOM_SETTING: …
      ...
```

and refer to it in the application resource like this:
```
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: myapp
spec:
  image: org/myapp:1.2.3
  ...
  configMaps:
    env:      
      - myapp-config
  ...
```

Naiserator will then mount the configmap on the PodSpec and make all the variables available for the application runtime.

### why?

- Give the developers with full control over the configuration their application is provided with, with no transformation or blackbox operations performed by either fasit or naisd. 
- Be able to grant the developers privileges to administer their *own* configuration in all environments (Fasit has a very coarse grained security model which makes this painful). 
- Leverage Kubernetes native mechanisms for handling configuration. 
- Reduce complexity by removing the deploy time dependency to Fasit. More robust.

It's up to each team how they choose to manage the configuration, however we should consider having some sort of centralized mechanism to handle it in the future.

Removing dependency to Fasit has some other implications that we need to address. Here are some of the issues that have come up that we discussed briefly in the user forum and should be further detailed in this issue.

> What about "service discovery" for services outside the cluster?

Having a deploy time service discovery mechanism (hence the quotes) does in some cases remove the need to notify your consumers if you change the URL of your applications endpoint (usually the path, the hostname is usually static and behind a VIP), and the other way around. This is not something we want to optimize for.
We think that this should be handled as a exception, by notifying consumers and keeping backwards compatibility if needed.

> Visibility of dependencies. Who uses the services my application exposes?  

Both Istio and AppDynamics give a runtime view of this. (Note: Istio is currently just available in GKE clusters, but should be available on-prem some time this fall)

/discuss
