### ISSUE TITLE
Support for reaching external hosts ports other than 443

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#153]
Users are currently unable to configure access to external hosts on other ports than 443.
Should be able to specify multiple ports.
When explicitly specifying ports, the default port 443 should not be included automatically

Suggested spec:

```
spec:
  accessPolicy:
    outbound:
      external:
        - host: www.external-application.com
           ports:
             - number: 1234
               protocol: HTTPS # https://istio.io/docs/reference/config/networking/gateway/#Port
```
