### ISSUE TITLE
Kunne skalere en app ned til 0

### ISSUE THREAD

**Issue by Kyrremann** [nais/naiserator#174]
Er flere som ønsker å kunne skalere appen sin ned til 0 midlertidig. Foreløpig er eneste løsning å slette app-en, og deploye på nytt.

For at dette skal fungere så må følgende fikses:

- [x]  FeatureGate HPAScaleToZero (skrudd på for onprem)
- [x] Naiseator tillater ikke replicas med `min: 0` og `max: 0`. Blir tolket som at du ikke har satt verdiene, og du får default (2 og 4)
- [ ] Vi bruker deklarativ HPA, som ikke støtter `spec.metrics` som trengs for å sette HPA til 0

Med team namespaces så kan man skalere ned deployment via `kubectl scale --replicas=0 deployment/foo`, selv om HPA vil være den samme. Så dette er også en mulig løsning.

Les mer om HPA i [Horizontal Pod Autoscaler Walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/).

Vi kan også ta en titt på [Scale subresource](https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#scale-subresource) for å tilby `kubectl scale` app-ressurser.

**Comment by jhrv** [comment]
> Vi bruker deklarativ HPA, som ikke støtter spec.metrics som trengs for å sette HPA til 0

Hva betyr det?

**Comment by Kyrremann** [comment]
For å kunne sette replicas til 0, så kan vi ikke bruke `targetCPUUtilizationPercentage`.
Så i stedet for:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: testapp
    team: aura
  name: testapp
  namespace: nais
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testapp
  targetCPUUtilizationPercentage: 50
```
må vi heller lage 
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: testapp
    team: aura
  name: testapp
  namespace: nais
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testapp
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```
