### ISSUE TITLE
Flatten healthcheck dict in Application spec

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#24]
```
healthcheck: 
    liveness: 
      path: isalive
    readiness: 
      path: isready
```

could be simplified to:
```
liveness: 
  path: isalive
readiness: 
  path: isready
```
