### ISSUE TITLE
Sette opp env-variabel for bucket-navn

### ISSUE THREAD

**Issue by baardkrk** [nais/naiserator#288]
Skulle gjerne kunnet hente environment variabel for bucket-navnet som blir provisjonert av applikasjonen. Noe á la `NAIS_DATABASE_{APPLICATION_NAME}_{DATABASE_NAME}` som finnes nå. 

Så f.eks. `NAIS_BUCKET_{APPLICATION_NAME}_{BUCKET_NAME}`

**Comment by baardkrk** [comment]
Ja, skjønner den. Var bare at jeg da hard-koder inn navnet på bucket’en inn i selve applikasjonen, så jeg må endre det både i appens konstanter og i nais-fila dersom det skal endres noen gang. 
Så hvis man f.eks. lager en library funksjon som håndterer å hente ting fra buckets må jeg også sende inn bucket-navnet til denne funksjonen

**Comment by jhrv** [comment]
Ser poenget. En mulighet kan være og sende inn valgt navn som en env-var, da blir det riktignok dobbelt opp i nais.yaml, men koden slipper å forholde seg til den konkrete verdien.

Mente ikke at vi ikke skulle gjøre det jeg foreslo heller, at vi kunne laget denne variabelen direkte men da enten med forutsetning at det kun er én bucket definert, eller med en indeks.

**Comment by ambientsound** [comment]
Praktisk eksempel @baardkrk:

`.nais/nais.yml`:
```
spec:
  env:
    - name: BUCKET_NAME
      value: {{ bucketName }}
  gcp:
    buckets:
      - name: {{ bucketName }}
```

Send inn bucket name i `VAR` med NAIS deploy:

`.github/workflows/deploy.yml`:
```
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: nais.yml
        VAR: image=${{ env.docker_image }},bucketName=foobarbaz
```
