### ISSUE TITLE
Expose Deployment RollingUpdate configurations

### ISSUE THREAD

**Issue by tronghn** [nais/naiserator#360]
Currently, the `rollingUpdate` configurations are hardcoded:

https://github.com/nais/naiserator/blob/1c7c696119477c330e6dbba96f7c376ee6c115a6/pkg/resourcecreator/deployment/deployment.go#L84-L97

Some users would like to be able to configure these themselves, e.g:

```yaml
[...]
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: "25%"
    maxUnavailable: 0
```

See also Slack discussion: https://nav-it.slack.com/archives/C5KUST8N6/p1669809786873019
