### ISSUE TITLE
internal.nav.no is treated as an external host

### ISSUE THREAD

**Issue by Starefossen** [nais/naiserator#374]
The following nais.yaml:

```yaml
apiVersion: nais.io/v1alpha1        
kind: Application    
metadata:                         
  labels:                    
    team: teamdagpenger
  name: dp-faktasider-frontend
  namespace: teamdagpenger
spec:           
  ingresses:                           
  - https://www.nav.no/arbeid/.+       
  - https://intern.nav.no/arbeid/.+                                            
```

Results in the following ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dp-faktasider-frontend-gw-nav-no-f7034580
  namespace: teamdagpenger
spec:
  ingressClassName: gw-nav-no
  rules:
  - host: www.nav.no
    http:
      paths:
      - backend:
          service:
            name: dp-faktasider-frontend
            port:
              number: 80
        path: /arbeid/.+(/.*)?
        pathType: ImplementationSpecific
  - host: intern.nav.no
    http:
      paths:
      - backend:
          service:
            name: dp-faktasider-frontend
            port:
              number: 80
        path: /arbeid/.+(/.*)?
        pathType: ImplementationSpecific
```

Mixing external and internal hosts under the same gateway.
