### ISSUE TITLE
Postgres database with dummy-name

### ISSUE THREAD

**Issue by thokra-nav** [nais/naiserator#422]
When I got the issue from #421, I tried to just remove the `name` part of my postgresql database:
```yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: test
  name: singledb-test
  namespace: test
spec:
  gcp:
    sqlInstances:
      - databases:
        type: POSTGRES_14
  image: ghcr.io/nais/up
```

(This spec was applied after I tried with a name that was already taken by another application)

This resultet in a database with the name `dummy-name` being created.
