### ISSUE TITLE
Add support for secure logs in applications

### ISSUE THREAD

**Issue by terjesannum** [nais/naiserator#56]
Some applications have logs with information that should not be stored with the normal application logs. To support this we need an additional method for getting these logs out of the application pods.

Add a flag in the application spec to enable this feature:

| Parameter | Description | Default | Required |
| --------- | ----------- | ------- | :--------: |
| spec.secure_logs.enabled | If true, mount a volume for secure logs in the pod | false |

This should add an emptyDir volume in the pod for the logs and add a sidecar for shipping the logs out of the pod (configured from a common configmap):

```yaml
volumes:
- name: secure-logs
  emptyDir:
    sizeLimit: 128M
- name: secure-logs-config
  configMap:
    name: secure-logs
```

Mount the secure-logs volume in the application pod:

```yaml
volumeMounts:
- name: secure-logs
  mountPath: /secure-logs
```

Add sidecars for shipping the logs and reload config on changes:

```yaml
containers:
- name: secure-logs-fluentd
  image: navikt/nais-logd@sha256:34735b486dd1766abe5f807cc40a4c3ca87ab1cfb0c4aac72e02c2eb2924871f
  imagePullPolicy: IfNotPresent
  volumeMounts:
  - name: secure-logs
    mountPath: /secure-logs
  - name: secure-logs-config
    mountPath: /fluentd/etc
    readOnly: true
  env:
    - name: NAIS_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: NAIS_APP
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['app']
    - name: NAIS_HOST
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: NAIS_TEAM
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['team']
- name: secure-logs-configmap-reload
  image: jimmidyson/configmap-reload@sha256:befec9f23d2a9da86a298d448cc9140f56a457362a7d9eecddba192db1ab489e
  imagePullPolicy: IfNotPresent
  args:
  - --volume-dir=/config
  - --webhook-url=http://localhost:24444/api/config.reload
  - --webhook-method=GET
  volumeMounts:
  - name: secure-logs-config
    mountPath: /config
    readOnly: true
```

**Comment by terjesannum** [comment]
The ca-bundle volume already present in the pod must also be mounted in the `secure-logs-fluentd` container:

```yaml
- mountPath: /etc/pki/tls/certs/ca-bundle.crt
  name: ca-bundle
  subPath: ca-bundle.pem
  readOnly: true
```
