### ISSUE TITLE
Liveness and readiness checks provide erroneous default values

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#64]
When not specifying all values, naiserator picks zero-val of type.

Example:
```
spec:
  ...
  liveness:
    path: /ping
  readiness:
    path: /ping
```

results in:
```
spec:
  ..
  liveness:
    failureThreshold: 0
    initialDelay: 0
    path: /ping
    periodSeconds: 0
    port: 0
    timeout: 0
  readiness:
    failureThreshold: 0
    initialDelay: 0
    path: /ping
    periodSeconds: 0
    port: 0
    timeout: 0
  ...
```

Which will not work. More sensible defaults should be set
