### ISSUE TITLE
Hardening: don't crash if one App doesn't have valid spec

### ISSUE THREAD

**Issue by VegarM** [nais/naiserator#66]
Found a bug where one app had the following spec (simplified):
```yaml
apiVersion: nais.io/v1alpha1
kind: Application
  name: name
spec:
  ingresses:
  - - https://url.com
...
```
Notice the double list in `ingresses`

which caused Naiserator to stop working completely, just logging: 
```
E0515 07:51:06.782937       1 reflector.go:131] pkg/mod/k8s.io/client-go@v0.0.0-20190408172623-b7e8408f656e/tools/cache/reflector.go:99: Failed to list *v1alpha1.Application: v1alpha1.ApplicationList.Items: []v1alpha1.Application: v1alpha1.Application.Spec: v1alpha1.ApplicationSpec.Ingresses: []string: ReadString: expects " or n, but found [, error found in #10 byte of ...|resses":[["https://n|..., bigger context ...|ge":"navikt/nav-dekoratoren:LATEST","ingresses":[["https://nav-dekoratoren.nais.preprod.local"]],"le|...
```
forever, not doing any work
