### ISSUE TITLE
Support native secrets 

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#71]
We should support native Kubernetes secrets

First draft of spec:

```
spec:
  ...
  secrets:
    - name: secret-with-envvars
    - name: secret-file
      mountPath: /var/run/secrets 
```

The example shows two examples of how to inject secrets into the pod. The first example, `secret-with-envvars` will inject all the key-value pairs in the secret as environment variables using `spec.containers[].envFrom.secretRef[]`. 
Second example, `secret-file` has the property `mountPath` signaling that the secret should be mounted as a read-only file under the provided path. The files in the secret will be made available to the application will then be `<mountPath>/<secret name>/<secret key>`

/discuss

**Comment by jhrv** [comment]
We might want to exclude the secret name from the mount path, effectively allowing the developers to place the files where they want. The initial thought was to avoid collisions, but this is a edge case I think is easily managed by the developers.

**Comment by ambientsound** [comment]
LGTM. Specifying `mounthPath` will magically transform this secret to a set of files instead of environment variables. Will this behavior feel natural to users?

**Comment by jhrv** [comment]
That was the original idea, but I don't think it's not a good one. I think we should model it more explicitly, but I've just not found a solution I like yet. Suggestions?

**Comment by jhrv** [comment]
if we add a optional type/mode, `mountAs` with a default value we get the same yaml for most cases.

```
  secrets:
    - name: secretasenv
      mountAs: env # default (so this can be omitted)
    - name: secretfiles
      mountAs: file # or files
      mountPath: /var/run/secrets
```

If we thought that it would be alot of different modes and options I would have suggested splitting out the list into the different types allowing for separate structs, but I think in this case it should be manageable having just a single list.

**Comment by Kyrremann** [comment]
Hvorfor ikke kopiere noe av oppsettet til Kubernetes? Prøve å holde det mest mulig likt, der hvor overheaded ikke er så stort. 

For eksempel, hvis man ønsker miljøvariabler, så kan vi gjenbruke oppsettet til `deployments`.
```
env:
  - name: SECRET_USERNAME
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: username
  - name: SECRET_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: password
```

Skal man ha det som filer, så syns jeg det å definere `volumes` og `volumeMounts` blir litt mye. Så mitt forslag der er å kun bruke `volumeMounts`.
```
volumeMounts:
    - name: foo # navnet på secreten din
      mountPath: "/etc/foo" # path hvor finne filen(e)
      readOnly: true # Trenger ikke denne, da vi vel kun vil støtter readOnly
```
Ulempen med sistnevnte, er at vi ikke kan skille mellom `secrets` og andre `volumes`. Så her kan/bør vi kanskje bytte `volumeMounts` til `secrets`.

**Comment by Kyrremann** [comment]
> That was the original idea, but I don't think it's not a good one. I think we should model it more explicitly, but I've just not found a solution I like yet. Suggestions?

Mener du her at du ikke liker oppførselen ved at `volumeMounts` ender opp som en fil per `key` i `secrets`?

**Comment by jhrv** [comment]
> > That was the original idea, but I don't think it's not a good one. I think we should model it more explicitly, but I've just not found a solution I like yet. Suggestions?

> Mener du her at du ikke liker oppførselen ved at volumeMounts ender opp som en fil per key i secrets?

Det jeg mente her var at jeg ikke likte at man endret oppførsel på hvordan hemmelighetene ble tilgjengeliggjort ved at man brukte et flagg som ikke tydelig sa at man ønsket det som filer. Det var en dårlig idé.

> Hvorfor ikke kopiere noe av oppsettet til Kubernetes? Prøve å holde det mest mulig likt, der hvor overheaded ikke er så stort.

Jeg liker forslaget å ha det bare rett i env, og det kan også være godt nok i første omgang. Mulighet for å ha det som filer kan vi støtte senere. Ulempen jeg ser med det er at det blir ganske mye ekstra YAML dersom man har mange secrets, da man må eksplisitt mappe én og én secret. Men syns likevel dette er et bedre forslag.

**Comment by ambientsound** [comment]
Re-using the configuration syntax from Kubernetes feels too verbose, and I'd argue that no one needs the level of flexibility this gives (i.e. renaming the environment variables).

Suggestion below based on @jhrv. This ensures that secrets can be mounted as both env and file. Renamed `mountAs` to `type`, and use plural `files` to emphasize that the keys in the secret will be used as file names.

```
secrets:
  - name: foo
  - name: lol
  - name: oeuoeu
  - name: baz
    type: env  # default
  - name: bar
    type: files
    mountPath: /var/run/secrets  # default
```
