### ISSUE TITLE
Revise accessPolicy spec before launch

### ISSUE THREAD

**Issue by jhrv** [nais/naiserator#78]
```
  accessPolicy:
    inbound:
      rules:
        - application: app1 # allows access from application a in same namespace
        - application: app2
          namespace: team_x # optional, defaults to 'metadata.namespace'
        - application: app3
          namespace: team_y
        - application: * # opens up for all inbound access from 'teamx' namespace
          namespace: team_z
    outbound:
      rules: 
        - application: app4
          namespace: team_a
      external: # cluster external hosts application needs to access
        - host: www.external-application.com
```

changes:

- ingress/egress changed to inbound/outbound as this is less ambiguous and more likely to be familiar terminology
- removed allowAll flag, and use "*" notation in application field in rules
- added external, a list of hosts allowed for outbound traffic 

/cc @linemos @ambientsound @frodesundby @matsbyfl
