### ISSUE TITLE
Prometheus needs access to istio enabled applications

### ISSUE THREAD

**Issue by terjesannum** [nais/naiserator#81]
Applications with prometheus scraping enabled must also grant access to`URI:spiffe://cluster.local/ns/istio-system/sa/default`

As if this was in the application specification:
```yaml
accessPolicy:
  ingress:
    rules:
      - application: default
        namespace: istio-system

```
